name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug"]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
      description: A clear description of the bug.
      placeholder: Describe what you expected vs what actually happened.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: How can we reproduce this?
      placeholder: |
        1. Start signal-tui with ...
        2. Run command ...
        3. See error ...
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true
  - type: input
    id: terminal
    attributes:
      label: Terminal emulator
      placeholder: e.g. Windows Terminal, iTerm2, Alacritty, kitty
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: signal-tui version
      placeholder: e.g. v0.2.0 or commit hash
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Paste any relevant output or attach screenshots.
    validations:
      required: false
